### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by ifischerova** [MijaHinn/PROJEKT-Kontakty#1]
Ahoj Míšo, 

super řešení 💯  Za sebe nemám nic, co bych na tom měnila, přijde mi, že to funguje jak má...a navíc jsem si  zase trochu rozšířila obzory (vlastnost row-gap):D Hodně se mi líbí i způsob, jak sis poradila s `flex` na `.kontaktech` u verze pro tablet. 🥇 

Kdybys měla čas a chuť, zkus to udělat úplně dle zadání, tj. že v mobilní verzi na `.kontaktech` nebude hned nastavený flexbox - podrobněji viz třetí až pátá odrážka v sekci Flexbox v README :)

**Comment by MijaHinn** [comment]
Ahoj, moc děkuji za zpětnou vazbu a za pochvalu :))) Když se u něčeho zaseknu, hodně si googlím.. takhle jsem objevila to `row-gap` a `column-gap`, což potom dost usnadní :D ..Kód jsem teda upravila, aby ta mobilní verze nebyla s tím flexboxem.  :)

**Comment by ifischerova** [comment]
Ahoj Míšo, super 👍 🥇
